version: "2.4"

services:
  app:
    # As soon as possible, get an image of your app on the github container registry
    # and use that image for local development. This will avoid drift between containers
    # on different machines.
    #
    # When that is ready, uncomment the next line, and delete the following two lines
    # and commit those changes to the repository.
    # image: ghcr.io/${{ github.repository }}:latest
    image: 990-db
    build: .
    container_name: 990-db
    # Allow container to be attached to, e.g., to access the pdb shell
    # env_file:
    #   - .env
    stdin_open: true
    tty: true
    ports:
      # Map ports on your computer to ports on your container. This allows you,
      # e.g., to visit your containerized application in a browser on your
      # computer.
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount the development directory as a volume into the container, so
      # Docker automatically recognizes your changes.
      - .:/app
      # Mount the node_modules directory so that our local mount doesn't
      # clobber it.
    environment:
      DJANGO_SECRET_KEY: reallysupersecret
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_DEBUG: "true"
    # entrypoint: /app/docker-entrypoint.sh
    working_dir: /app/irsdb
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: 990-db-postgres
    image: postgres:11
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # The default Postgres image exposes a number of environmental variables
      # that allow you to configure the container's behavior, without writing
      # any additional code. Specify the name of your database, and any other
      # variables, here. https://hub.docker.com/_/postgres/#environment-variables
      POSTGRES_DB: database
      POSTGRES_PASSWORD: postgres
    volumes:
      # By default, Postgres instantiates an anonymous volume. Use a named
      # one, so your data persists beyond the life of the container. See this
      # post for a discussion of the pitfalls of Postgres and anonymous
      # volumes: https://linuxhint.com/run_postgresql_docker_compose/
      - 990-db-data:/var/lib/postgresql/data
    ports:
      - 32001:5432

volumes:
  # Declare your named volume for Postgres.
  990-db-data:
  # Making node_modules a named volume prevents the ./app volume mount from
  # clobbering the directory in the container.
